### DoorDash Investment Analysis

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns # <- would you have guessed sns ?

In [3]:
# df = pd.read_csv("../Group Assignment/DASH_A1.csv")
df = pd.read_csv("DASH_A1.csv")
df

            Date       Close        High         Low        Open     Volume
0     24-02-2022  100.419998  100.919998   85.177002   86.879997  6639000.0
1     01-08-2024  108.199997  112.769997  105.905998  108.620003  7965400.0
2     11-02-2025  193.089996  194.000000  189.500000  190.919998  6771900.0
3     13-04-2021  149.460007  150.360001  143.550003  146.839996  2823500.0
4     17-09-2024  129.880005  131.369995  126.900002  131.350006  2825500.0
...          ...         ...         ...         ...         ...        ...
1179  27-11-2024  178.440002  180.179993  177.699997  179.990005  2031100.0
1180  12-02-2025  200.889999  201.169998  195.197998  198.000000  9989400.0
1181  01-04-2025  182.419998  183.014999  178.259995  182.050003  3740700.0
1182  25-03-2024  137.820007  138.899994  136.740005  137.050003  2162800.0
1183  26-03-2025  192.869995  199.669998  191.460007  199.240005  3848800.0

[1184 rows x 6 columns]

In [4]:
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)
df.set_index("Date", inplace=True)
df

                 Close        High         Low        Open     Volume
Date
2022-02-24  100.419998  100.919998   85.177002   86.879997  6639000.0
2024-08-01  108.199997  112.769997  105.905998  108.620003  7965400.0
2025-02-11  193.089996  194.000000  189.500000  190.919998  6771900.0
2021-04-13  149.460007  150.360001  143.550003  146.839996  2823500.0
2024-09-17  129.880005  131.369995  126.900002  131.350006  2825500.0
...                ...         ...         ...         ...        ...
2024-11-27  178.440002  180.179993  177.699997  179.990005  2031100.0
2025-02-12  200.889999  201.169998  195.197998  198.000000  9989400.0
2025-04-01  182.419998  183.014999  178.259995  182.050003  3740700.0
2024-03-25  137.820007  138.899994  136.740005  137.050003  2162800.0
2025-03-26  192.869995  199.669998  191.460007  199.240005  3848800.0

[1184 rows x 5 columns]

In [5]:
df[df.isnull().any(axis=1)]

                 Close        High         Low        Open     Volume
Date
2023-09-28   77.800003   79.739998   76.599998   77.110001        NaN
2022-05-02   82.260002   85.370003   78.790001   81.620003        NaN
2021-08-02         NaN  179.529999  169.800003  175.350006        NaN
2022-03-29  123.550003  125.110001  115.459999         NaN  5660300.0
2021-12-02  166.119995         NaN  160.289993  163.509995  3866800.0
...                ...         ...         ...         ...        ...
2025-01-08  173.720001         NaN  169.860001  171.199997  2189400.0
2024-05-10  114.839996         NaN  114.099998  116.720001  4407000.0
2021-11-04         NaN  209.580002  204.270004  207.250000  1387100.0
2025-05-02  205.089996         NaN  199.429993  200.070007        NaN
2022-03-29  123.550003  125.110001  115.459999         NaN  5660300.0

[99 rows x 5 columns]

In [6]:
df.sort_index(inplace=True)

df['Open'] = df['Open'].fillna(df['Close'].shift(1))
df

                 Close        High         Low        Open      Volume
Date
2020-12-09  189.509995  195.500000  163.800003  182.000000  25373700.0
2020-12-10  186.000000  187.695007  172.636002  179.710007         NaN
2020-12-11  175.000000  182.000000  168.250000  176.520004   4760600.0
2020-12-14  160.000000  170.000000  151.199997  169.100006   7859600.0
2020-12-15  158.889999  161.419998  153.759995  157.100006   5017000.0
...                ...         ...         ...         ...         ...
2025-06-09  217.490005  219.830002  216.955002  218.029999   2710300.0
2025-06-10  214.970001  219.210007  210.927002  216.589996   3916700.0
2025-06-11  217.800003  219.529999  212.240005  214.184998   3091500.0
2025-06-12  216.600006  219.419998  215.675003  218.080002   2510400.0
2025-06-13  218.119995  218.299896  213.000000  214.190002    616326.0

[1184 rows x 5 columns]

In [7]:
df['Close'] = df["Close"].ffill()
df

                 Close        High         Low        Open      Volume
Date
2020-12-09  189.509995  195.500000  163.800003  182.000000  25373700.0
2020-12-10  186.000000  187.695007  172.636002  179.710007         NaN
2020-12-11  175.000000  182.000000  168.250000  176.520004   4760600.0
2020-12-14  160.000000  170.000000  151.199997  169.100006   7859600.0
2020-12-15  158.889999  161.419998  153.759995  157.100006   5017000.0
...                ...         ...         ...         ...         ...
2025-06-09  217.490005  219.830002  216.955002  218.029999   2710300.0
2025-06-10  214.970001  219.210007  210.927002  216.589996   3916700.0
2025-06-11  217.800003  219.529999  212.240005  214.184998   3091500.0
2025-06-12  216.600006  219.419998  215.675003  218.080002   2510400.0
2025-06-13  218.119995  218.299896  213.000000  214.190002    616326.0

[1184 rows x 5 columns]

In [8]:
df["High"] = df["High"].interpolate(method="linear")
df["Low"] = df["Low"].interpolate(method="linear")

df

                 Close        High         Low        Open      Volume
Date
2020-12-09  189.509995  195.500000  163.800003  182.000000  25373700.0
2020-12-10  186.000000  187.695007  172.636002  179.710007         NaN
2020-12-11  175.000000  182.000000  168.250000  176.520004   4760600.0
2020-12-14  160.000000  170.000000  151.199997  169.100006   7859600.0
2020-12-15  158.889999  161.419998  153.759995  157.100006   5017000.0
...                ...         ...         ...         ...         ...
2025-06-09  217.490005  219.830002  216.955002  218.029999   2710300.0
2025-06-10  214.970001  219.210007  210.927002  216.589996   3916700.0
2025-06-11  217.800003  219.529999  212.240005  214.184998   3091500.0
2025-06-12  216.600006  219.419998  215.675003  218.080002   2510400.0
2025-06-13  218.119995  218.299896  213.000000  214.190002    616326.0

[1184 rows x 5 columns]

In [9]:
rows_zero = df.loc[df["Open"].eq(df["Close"])]
rows_zero

                 Close        High         Low        Open     Volume
Date
2022-03-23  114.339996  116.809998  107.164001  114.339996  3635200.0
2022-03-29  123.550003  125.110001  115.459999  123.550003  5660300.0
2025-01-09  173.720001  173.426005  168.840004  173.720001        NaN

In [10]:
zeroVol = df['Volume'].isna() & (df["Open"] == df["Close"])
df.loc [zeroVol, 'Volume'] = 0

df

                 Close        High         Low        Open      Volume
Date
2020-12-09  189.509995  195.500000  163.800003  182.000000  25373700.0
2020-12-10  186.000000  187.695007  172.636002  179.710007         NaN
2020-12-11  175.000000  182.000000  168.250000  176.520004   4760600.0
2020-12-14  160.000000  170.000000  151.199997  169.100006   7859600.0
2020-12-15  158.889999  161.419998  153.759995  157.100006   5017000.0
...                ...         ...         ...         ...         ...
2025-06-09  217.490005  219.830002  216.955002  218.029999   2710300.0
2025-06-10  214.970001  219.210007  210.927002  216.589996   3916700.0
2025-06-11  217.800003  219.529999  212.240005  214.184998   3091500.0
2025-06-12  216.600006  219.419998  215.675003  218.080002   2510400.0
2025-06-13  218.119995  218.299896  213.000000  214.190002    616326.0

[1184 rows x 5 columns]

In [11]:
rows_zero = df.loc[df["Open"].eq(df["Close"])]
rows_zero

                 Close        High         Low        Open     Volume
Date
2022-03-23  114.339996  116.809998  107.164001  114.339996  3635200.0
2022-03-29  123.550003  125.110001  115.459999  123.550003  5660300.0
2025-01-09  173.720001  173.426005  168.840004  173.720001        0.0

In [12]:
median_test = df.loc[df['Volume'].isna() & (df["Open"] != df["Close"])]
median_test

                 Close        High         Low        Open  Volume
Date
2020-12-10  186.000000  187.695007  172.636002  179.710007     NaN
2021-03-01  168.889999  173.789993  164.199997  171.440002     NaN
2021-07-09  178.559998  181.649994  176.539993  180.660004     NaN
2021-08-02  174.289993  179.529999  169.800003  175.350006     NaN
2021-08-25  188.250000  190.119995  184.550003  185.449997     NaN
2021-10-08  204.419998  207.990005  204.149994  204.899994     NaN
2022-05-02   82.260002   85.370003   78.790001   81.620003     NaN
2022-07-25   71.760002   74.820000   70.349998   73.120003     NaN
2022-10-24   44.430000   44.959999   41.365002   44.599998     NaN
2022-11-23   56.580002   57.090000   53.689999   54.610001     NaN
2022-12-12   58.020000   58.060001   55.299999   55.590000     NaN
2022-12-23   50.689999   51.230000   49.755001   50.970001     NaN
2023-02-06   59.680000   61.205000   58.009998   58.020000     NaN
2023-02-21   58.060001   60.860001   57.220001   59.970001     NaN
2023-05-01   62.200001   62.875000   60.450001   60.930000     NaN
2023-05-16   64.180000   65.809998   63.730000   65.550003     NaN
2023-09-28   77.800003   79.739998   76.599998   77.110001     NaN
2023-11-17   95.230003   95.697998   94.260002   95.540001     NaN
2024-01-19  106.330002  106.559998  103.599998  105.320000     NaN
2024-06-06  114.070000  114.422997  110.910004  110.930000     NaN
2024-08-07  121.489998  126.370003  121.410004  123.809998     NaN
2024-09-06  123.559998  126.410004  122.320000  126.070000     NaN
2024-10-02  143.580002  144.354996  141.574997  141.899994     NaN
2025-01-22  177.679993  180.000000  177.360001  179.669998     NaN
2025-05-02  205.089996  202.489998  199.429993  200.070007     NaN

In [13]:
median_vol =df["Volume"].median()
median_test = df['Volume'].isna() & (df["Open"] != df["Close"])

df.loc[median_test,"Volume"] = median_vol

#Test
print(df.Volume, '2020-12-20')

Date
2020-12-09    25373700.0
2020-12-10     3506600.0
2020-12-11     4760600.0
2020-12-14     7859600.0
2020-12-15     5017000.0
                 ...
2025-06-09     2710300.0
2025-06-10     3916700.0
2025-06-11     3091500.0
2025-06-12     2510400.0
2025-06-13      616326.0
Name: Volume, Length: 1184, dtype: float64 2020-12-20

In [14]:
median_test

Date
2020-12-09    False
2020-12-10     True
2020-12-11    False
2020-12-14    False
2020-12-15    False
              ...
2025-06-09    False
2025-06-10    False
2025-06-11    False
2025-06-12    False
2025-06-13    False
Length: 1184, dtype: bool

## Enginering

In [15]:
df.head()

                 Close        High         Low        Open      Volume
Date
2020-12-09  189.509995  195.500000  163.800003  182.000000  25373700.0
2020-12-10  186.000000  187.695007  172.636002  179.710007   3506600.0
2020-12-11  175.000000  182.000000  168.250000  176.520004   4760600.0
2020-12-14  160.000000  170.000000  151.199997  169.100006   7859600.0
2020-12-15  158.889999  161.419998  153.759995  157.100006   5017000.0

In [16]:
# 1. Calculate simple daily returns
df['DailyReturn'] = df['Close'].pct_change()
df

,Close,High,Low,Open,Volume,DailyReturn
Date,,,,,,
2020-12-09,189.509995,195.500000,163.800003,182.000000,25373700.0,NaN
2020-12-10,186.000000,187.695007,172.636002,179.710007,3506600.0,-0.018521
2020-12-11,175.000000,182.000000,168.250000,176.520004,4760600.0,-0.059140
2020-12-14,160.000000,170.000000,151.199997,169.100006,7859600.0,-0.085714
2020-12-15,158.889999,161.419998,153.759995,157.100006,5017000.0,-0.006938
...,...,...,...,...,...,...
2025-06-09,217.490005,219.830002,216.955002,218.029999,2710300.0,-0.004395
2025-06-10,214.970001,219.210007,210.927002,216.589996,3916700.0,-0.011587
2025-06-11,217.800003,219.529999,212.240005,214.184998,3091500.0,0.013165
2025-06-12,216.600006,219.419998,215.675003,218.080002,2510400.0,-0.005510
2025-06-13,218.119995,218.299896,213.000000,214.190002,616326.0,0.007017

In [17]:
# 2. Calculate the logarithmic returns
df['LogReturn'] = np.log(df['Close'] / df['Close'].shift(1))
df

,Close,High,Low,Open,Volume,DailyReturn,LogReturn
Date,,,,,,,
2020-12-09,189.509995,195.500000,163.800003,182.000000,25373700.0,NaN,NaN
2020-12-10,186.000000,187.695007,172.636002,179.710007,3506600.0,-0.018521,-0.018695
2020-12-11,175.000000,182.000000,168.250000,176.520004,4760600.0,-0.059140,-0.060961
2020-12-14,160.000000,170.000000,151.199997,169.100006,7859600.0,-0.085714,-0.089612
2020-12-15,158.889999,161.419998,153.759995,157.100006,5017000.0,-0.006938,-0.006962
...,...,...,...,...,...,...,...
2025-06-09,217.490005,219.830002,216.955002,218.029999,2710300.0,-0.004395,-0.004404
2025-06-10,214.970001,219.210007,210.927002,216.589996,3916700.0,-0.011587,-0.011654
2025-06-11,217.800003,219.529999,212.240005,214.184998,3091500.0,0.013165,0.013079
2025-06-12,216.600006,219.419998,215.675003,218.080002,2510400.0,-0.005510,-0.005525
2025-06-13,218.119995,218.299896,213.000000,214.190002,616326.0,0.007017,0.006993

In [18]:
# 3. Calculate 20-day momentum
df['Momentum'] = df['Close'] - df['Close'].shift(20)
df

,Close,High,Low,Open,Volume,DailyReturn,LogReturn,Momentum
Date,,,,,,,,
2020-12-09,189.509995,195.500000,163.800003,182.000000,25373700.0,NaN,NaN,NaN
2020-12-10,186.000000,187.695007,172.636002,179.710007,3506600.0,-0.018521,-0.018695,NaN
2020-12-11,175.000000,182.000000,168.250000,176.520004,4760600.0,-0.059140,-0.060961,NaN
2020-12-14,160.000000,170.000000,151.199997,169.100006,7859600.0,-0.085714,-0.089612,NaN
2020-12-15,158.889999,161.419998,153.759995,157.100006,5017000.0,-0.006938,-0.006962,NaN
...,...,...,...,...,...,...,...,...
2025-06-09,217.490005,219.830002,216.955002,218.029999,2710300.0,-0.004395,-0.004404,33.970001
2025-06-10,214.970001,219.210007,210.927002,216.589996,3916700.0,-0.011587,-0.011654,22.869995
2025-06-11,217.800003,219.529999,212.240005,214.184998,3091500.0,0.013165,0.013079,20.000000
2025-06-12,216.600006,219.419998,215.675003,218.080002,2510400.0,-0.005510,-0.005525,19.760010
2025-06-13,218.119995,218.299896,213.000000,214.190002,616326.0,0.007017,0.006993,21.019989

In [19]:
# 4. Calculate 20-day Simple Moving Average
df['SMA'] = df['Close'].rolling(window=20).mean()
df

,Close,High,Low,Open,Volume,DailyReturn,LogReturn,Momentum,SMA
Date,,,,,,,,,
2020-12-09,189.509995,195.500000,163.800003,182.000000,25373700.0,NaN,NaN,NaN,NaN
2020-12-10,186.000000,187.695007,172.636002,179.710007,3506600.0,-0.018521,-0.018695,NaN,NaN
2020-12-11,175.000000,182.000000,168.250000,176.520004,4760600.0,-0.059140,-0.060961,NaN,NaN
2020-12-14,160.000000,170.000000,151.199997,169.100006,7859600.0,-0.085714,-0.089612,NaN,NaN
2020-12-15,158.889999,161.419998,153.759995,157.100006,5017000.0,-0.006938,-0.006962,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2025-06-09,217.490005,219.830002,216.955002,218.029999,2710300.0,-0.004395,-0.004404,33.970001,206.409998
2025-06-10,214.970001,219.210007,210.927002,216.589996,3916700.0,-0.011587,-0.011654,22.869995,207.553498
2025-06-11,217.800003,219.529999,212.240005,214.184998,3091500.0,0.013165,0.013079,20.000000,208.553498
2025-06-12,216.600006,219.419998,215.675003,218.080002,2510400.0,-0.005510,-0.005525,19.760010,209.541499
2025-06-13,218.119995,218.299896,213.000000,214.190002,616326.0,0.007017,0.006993,21.019989,210.592498

In [20]:
# 5. Calculate 20-Day Rolling Volatility

df['RollingVolatility'] = df['DailyReturn'].rolling(window=20).std() 
df

,Close,High,Low,Open,Volume,DailyReturn,LogReturn,Momentum,SMA,RollingVolatility
Date,,,,,,,,,,
2020-12-09,189.509995,195.500000,163.800003,182.000000,25373700.0,NaN,NaN,NaN,NaN,NaN
2020-12-10,186.000000,187.695007,172.636002,179.710007,3506600.0,-0.018521,-0.018695,NaN,NaN,NaN
2020-12-11,175.000000,182.000000,168.250000,176.520004,4760600.0,-0.059140,-0.060961,NaN,NaN,NaN
2020-12-14,160.000000,170.000000,151.199997,169.100006,7859600.0,-0.085714,-0.089612,NaN,NaN,NaN
2020-12-15,158.889999,161.419998,153.759995,157.100006,5017000.0,-0.006938,-0.006962,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2025-06-09,217.490005,219.830002,216.955002,218.029999,2710300.0,-0.004395,-0.004404,33.970001,206.409998,0.017753
2025-06-10,214.970001,219.210007,210.927002,216.589996,3916700.0,-0.011587,-0.011654,22.869995,207.553498,0.015859
2025-06-11,217.800003,219.529999,212.240005,214.184998,3091500.0,0.013165,0.013079,20.000000,208.553498,0.014953
2025-06-12,216.600006,219.419998,215.675003,218.080002,2510400.0,-0.005510,-0.005525,19.760010,209.541499,0.014976
2025-06-13,218.119995,218.299896,213.000000,214.190002,616326.0,0.007017,0.006993,21.019989,210.592498,0.014958

In [21]:
# 6. Identify the day of the week
df['DayofWeek'] = df.index.day_name()
df

,Close,High,Low,Open,Volume,DailyReturn,LogReturn,Momentum,SMA,RollingVolatility,DayofWeek
Date,,,,,,,,,,,
2020-12-09,189.509995,195.500000,163.800003,182.000000,25373700.0,NaN,NaN,NaN,NaN,NaN,Wednesday
2020-12-10,186.000000,187.695007,172.636002,179.710007,3506600.0,-0.018521,-0.018695,NaN,NaN,NaN,Thursday
2020-12-11,175.000000,182.000000,168.250000,176.520004,4760600.0,-0.059140,-0.060961,NaN,NaN,NaN,Friday
2020-12-14,160.000000,170.000000,151.199997,169.100006,7859600.0,-0.085714,-0.089612,NaN,NaN,NaN,Monday
2020-12-15,158.889999,161.419998,153.759995,157.100006,5017000.0,-0.006938,-0.006962,NaN,NaN,NaN,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...
2025-06-09,217.490005,219.830002,216.955002,218.029999,2710300.0,-0.004395,-0.004404,33.970001,206.409998,0.017753,Monday
2025-06-10,214.970001,219.210007,210.927002,216.589996,3916700.0,-0.011587,-0.011654,22.869995,207.553498,0.015859,Tuesday
2025-06-11,217.800003,219.529999,212.240005,214.184998,3091500.0,0.013165,0.013079,20.000000,208.553498,0.014953,Wednesday
2025-06-12,216.600006,219.419998,215.675003,218.080002,2510400.0,-0.005510,-0.005525,19.760010,209.541499,0.014976,Thursday
2025-06-13,218.119995,218.299896,213.000000,214.190002,616326.0,0.007017,0.006993,21.019989,210.592498,0.014958,Friday

## Key Dates

In [22]:
# 1. Highest Volatility Day
df['Vol'] = df['Close'].pct_change().rolling(window=30).std()
summary = (df.assign(Year=df.index.year).groupby('Year')['Vol'].agg(PeakVol='max', PeakDate=lambda s: s.idxmax()).reset_index())
print(summary)

   Year   PeakVol   PeakDate
0  2020       NaN        NaT
1  2021  0.063320 2021-02-22
2  2022  0.073903 2022-03-16
3  2023  0.043803 2023-02-23
4  2024  0.028619 2024-08-13
5  2025  0.043962 2025-05-07

/tmp/ipykernel_6004/2323029301.py:3: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  summary = (df.assign(Year=df.index.year).groupby('Year')['Vol'].agg(PeakVol='max', PeakDate=lambda s: s.idxmax()).reset_index())

In [23]:
# 2. Largest Price Surge Day
df['DailyReturn'] = df['Close'].pct_change()
summary = (df.assign(Year=df.index.year).groupby('Year')['DailyReturn'].agg(PeakReturn='max', PeakDate=lambda s: s.idxmax()).reset_index())
print(summary)

   Year  PeakReturn   PeakDate
0  2020    0.078724 2020-12-18
1  2021    0.221491 2021-05-14
2  2022    0.134512 2022-03-16
3  2023    0.156653 2023-11-02
4  2024    0.083457 2024-08-02
5  2025    0.137738 2025-04-09

In [24]:
# 3. Largest Price Drop Day
drop_day = (df.groupby(df.index.year)['DailyReturn'].agg(DropValue='min', DropDate=lambda s: s.idxmin()).reset_index(names='Year'))
print(drop_day)

   Year  DropValue   DropDate
0  2020  -0.085714 2020-12-14
1  2021  -0.135457 2021-02-22
2  2022  -0.131621 2022-05-11
3  2023  -0.075946 2023-02-17
4  2024  -0.103170 2024-05-02
5  2025  -0.080634 2025-04-03

In [25]:
# 4. Highest Volume Day
highest_volume_per_year = (df.groupby(df.index.year)['Volume'].agg(MaxVolume='max',  MaxDate=lambda s: s.idxmax()).reset_index(names='Year'))
print(highest_volume_per_year)

   Year   MaxVolume    MaxDate
0  2020  25373700.0 2020-12-09
1  2021  20400000.0 2021-03-09
2  2022  47405700.0 2022-02-17
3  2023  30556000.0 2023-12-15
4  2024  22134800.0 2024-05-02
5  2025  73637400.0 2025-03-21

In [26]:
# 5. Highest High and Lowest Low
hi_lo_per_year = (
    df.groupby(df.index.year)
      .agg(HighestHigh=('High', 'max'), HighDate   =('High', lambda s: s.idxmax()), LowestLow  =('Low',  'min'), LowDate    =('Low',  lambda s: s.idxmin()))
      .reset_index(names='Year'))
print(hi_lo_per_year)

   Year  HighestHigh   HighDate   LowestLow    LowDate
0  2020   195.500000 2020-12-09  135.380005 2020-12-31
1  2021   257.250000 2021-11-15  110.129997 2021-05-13
2  2022   152.494995 2022-01-12   41.365002 2022-10-24
3  2023   103.980003 2023-12-11   45.931999 2023-01-06
4  2024   181.779999 2024-12-17   93.330002 2024-01-04
5  2025   220.880005 2025-06-06  155.399994 2025-04-07

In [27]:
# 6. Annual Open and Close
annual_open_close = (df.groupby(df.index.year).agg(YearOpen=('Open', 'first'),YearClose=('Close', 'last')).reset_index(names='Year'))
print(annual_open_close)

   Year    YearOpen   YearClose
0  2020  182.000000  142.750000
1  2021  142.500000  148.899994
2  2022  149.610001   48.820000
3  2023   49.980000   98.889999
4  2024   97.800003  167.750000
5  2025  168.789993  218.119995